# Generated by Django 4.2.7 on 2023-12-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_city_alter_listing_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='region',
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
